<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 Supervised Methods | Quantitative Text Analysis</title>
  <meta name="description" content="Theory and Methods for Quantitative Text Analysis" />
  <meta name="generator" content="bookdown 0.21 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 Supervised Methods | Quantitative Text Analysis" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Theory and Methods for Quantitative Text Analysis" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 Supervised Methods | Quantitative Text Analysis" />
  
  <meta name="twitter:description" content="Theory and Methods for Quantitative Text Analysis" />
  

<meta name="author" content="Kostas Gemenis &amp; Bastiaan Bruinsma" />


<meta name="date" content="2021-03-26" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="scaling.html"/>
<link rel="next" href="unsupervised-methods.html"/>
<script src="libs/header-attrs-2.7/header-attrs.js"></script>
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />











<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Intro to Quantitative Text Analysis</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Foreword</a></li>
<li class="chapter" data-level="2" data-path="getting-ready.html"><a href="getting-ready.html"><i class="fa fa-check"></i><b>2</b> Getting Ready</a>
<ul>
<li class="chapter" data-level="2.1" data-path="getting-ready.html"><a href="getting-ready.html#installing-r"><i class="fa fa-check"></i><b>2.1</b> Installing R</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="getting-ready.html"><a href="getting-ready.html#r-on-windows"><i class="fa fa-check"></i><b>2.1.1</b> R on Windows</a></li>
<li class="chapter" data-level="2.1.2" data-path="getting-ready.html"><a href="getting-ready.html#r-on-linux"><i class="fa fa-check"></i><b>2.1.2</b> R on Linux</a></li>
<li class="chapter" data-level="2.1.3" data-path="getting-ready.html"><a href="getting-ready.html#r-on-macos"><i class="fa fa-check"></i><b>2.1.3</b> R on macOS</a></li>
<li class="chapter" data-level="2.1.4" data-path="getting-ready.html"><a href="getting-ready.html#r-in-the-cloud"><i class="fa fa-check"></i><b>2.1.4</b> R in the Cloud</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="getting-ready.html"><a href="getting-ready.html#packages"><i class="fa fa-check"></i><b>2.2</b> Packages</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="getting-ready.html"><a href="getting-ready.html#installing-from-cran"><i class="fa fa-check"></i><b>2.2.1</b> Installing from CRAN</a></li>
<li class="chapter" data-level="2.2.2" data-path="getting-ready.html"><a href="getting-ready.html#installing-from-github"><i class="fa fa-check"></i><b>2.2.2</b> Installing from GitHub</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="getting-ready.html"><a href="getting-ready.html#quanteda"><i class="fa fa-check"></i><b>2.3</b> Quanteda</a></li>
<li class="chapter" data-level="2.4" data-path="getting-ready.html"><a href="getting-ready.html#issues-bugs-and-errors"><i class="fa fa-check"></i><b>2.4</b> Issues, Bugs and Errors</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="preparing-the-data.html"><a href="preparing-the-data.html"><i class="fa fa-check"></i><b>3</b> Preparing the Data</a>
<ul>
<li class="chapter" data-level="3.1" data-path="preparing-the-data.html"><a href="preparing-the-data.html#text-in-r"><i class="fa fa-check"></i><b>3.1</b> Text in R</a></li>
<li class="chapter" data-level="3.2" data-path="preparing-the-data.html"><a href="preparing-the-data.html#import-.pdf-files"><i class="fa fa-check"></i><b>3.2</b> Import .pdf Files</a></li>
<li class="chapter" data-level="3.3" data-path="preparing-the-data.html"><a href="preparing-the-data.html#import-.txt-files"><i class="fa fa-check"></i><b>3.3</b> Import .txt Files</a></li>
<li class="chapter" data-level="3.4" data-path="preparing-the-data.html"><a href="preparing-the-data.html#import-.csv-files"><i class="fa fa-check"></i><b>3.4</b> Import .csv Files</a></li>
<li class="chapter" data-level="3.5" data-path="preparing-the-data.html"><a href="preparing-the-data.html#import-using-web-scraping"><i class="fa fa-check"></i><b>3.5</b> Import using Web Scraping</a></li>
<li class="chapter" data-level="3.6" data-path="preparing-the-data.html"><a href="preparing-the-data.html#import-from-an-api"><i class="fa fa-check"></i><b>3.6</b> Import from an API</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="reliability-and-validity.html"><a href="reliability-and-validity.html"><i class="fa fa-check"></i><b>4</b> Reliability and validity</a>
<ul>
<li class="chapter" data-level="4.1" data-path="reliability-and-validity.html"><a href="reliability-and-validity.html#measuring-inter-coder-agreement"><i class="fa fa-check"></i><b>4.1</b> Measuring inter-coder agreement</a></li>
<li class="chapter" data-level="4.2" data-path="reliability-and-validity.html"><a href="reliability-and-validity.html#visualizing-the-quality-of-coding"><i class="fa fa-check"></i><b>4.2</b> Visualizing the quality of coding</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="dictionaries.html"><a href="dictionaries.html"><i class="fa fa-check"></i><b>5</b> Dictionaries</a>
<ul>
<li class="chapter" data-level="5.1" data-path="dictionaries.html"><a href="dictionaries.html#working-with-a-corpus"><i class="fa fa-check"></i><b>5.1</b> Working with a Corpus</a></li>
<li class="chapter" data-level="5.2" data-path="dictionaries.html"><a href="dictionaries.html#standard-dictionary-analysis"><i class="fa fa-check"></i><b>5.2</b> Standard Dictionary Analysis</a></li>
<li class="chapter" data-level="5.3" data-path="dictionaries.html"><a href="dictionaries.html#sentiment-analysis"><i class="fa fa-check"></i><b>5.3</b> Sentiment Analysis</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="scaling.html"><a href="scaling.html"><i class="fa fa-check"></i><b>6</b> Scaling</a>
<ul>
<li class="chapter" data-level="6.1" data-path="scaling.html"><a href="scaling.html#wordscores"><i class="fa fa-check"></i><b>6.1</b> Wordscores</a></li>
<li class="chapter" data-level="6.2" data-path="scaling.html"><a href="scaling.html#wordfish"><i class="fa fa-check"></i><b>6.2</b> Wordfish</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="supervised-methods.html"><a href="supervised-methods.html"><i class="fa fa-check"></i><b>7</b> Supervised Methods</a>
<ul>
<li class="chapter" data-level="7.1" data-path="supervised-methods.html"><a href="supervised-methods.html#support-vector-machines"><i class="fa fa-check"></i><b>7.1</b> Support Vector Machines</a></li>
<li class="chapter" data-level="7.2" data-path="supervised-methods.html"><a href="supervised-methods.html#naive-bayes"><i class="fa fa-check"></i><b>7.2</b> Naive Bayes</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="unsupervised-methods.html"><a href="unsupervised-methods.html"><i class="fa fa-check"></i><b>8</b> Unsupervised Methods</a>
<ul>
<li class="chapter" data-level="8.1" data-path="unsupervised-methods.html"><a href="unsupervised-methods.html#latent-dirichlet-allocation"><i class="fa fa-check"></i><b>8.1</b> Latent Dirichlet Allocation</a></li>
<li class="chapter" data-level="8.2" data-path="unsupervised-methods.html"><a href="unsupervised-methods.html#correspondence-analysis"><i class="fa fa-check"></i><b>8.2</b> Correspondence Analysis</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="bruinsma@soz.uni-frankfurt.de" target="blank">Bastiaan Bruinsma</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Quantitative Text Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="supervised-methods" class="section level1" number="7">
<h1><span class="header-section-number">Chapter 7</span> Supervised Methods</h1>
<p>While with scaling we try to place our texts on a scale, with supervised methods we go back to what we did with dictionary analysis: classification. Within <code>quanteda</code> there are many different models for supervised methods, of which we will cover two. These are Support Vector Machines (SVM) and Naive Bayes (NB). The first classifies texts by looking at their position on a hyperplane, the second by their (Bayesian) probabilities. To show how they work, we will look at an example of SVM in <code>quanteda</code> and one in <code>RTextTools</code>, and an example of NB in <code>quanteda</code>.</p>
<div id="support-vector-machines" class="section level2" number="7.1">
<h2><span class="header-section-number">7.1</span> Support Vector Machines</h2>
<p>For the SVM, we will start with a textbook example using a dataset that comes with <code>RTextTools</code> package. The US Congress dataset contains 1000 sentences drawn from bills debated in the 107 US Congress. With the following commands we load and view the US Congress data:</p>
<div class="sourceCode" id="cb130"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb130-1"><a href="supervised-methods.html#cb130-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;RTextTools&quot;</span>)</span></code></pre></div>
<pre><code>## Carico il pacchetto richiesto: SparseM</code></pre>
<pre><code>## 
## Attaching package: &#39;SparseM&#39;</code></pre>
<pre><code>## The following object is masked from &#39;package:base&#39;:
## 
##     backsolve</code></pre>
<pre><code>## Registered S3 method overwritten by &#39;tree&#39;:
##   method     from
##   print.tree cli</code></pre>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="supervised-methods.html#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(USCongress)</span></code></pre></div>
<p>As you can see, the variable <code>text</code> corresponds to sentences (one per row) while the variable <code>major</code> corresponds to a category that was manually coded for each of these sentences. The goal of the supervised learning task is to use part of this dataset to train a certain algorithm, and then use the trained algorithm to assign categories to the remaining sentences. Since we know the coded categories for the remaining sentences, we will be able to evaluate how well this training was in guessing/estimating what the codes for these sentences were. We start by creating a document term matrix. The options specified in the command instruct R to look into the <code>text</code> variable and remove numbers, stem words, and remove words that appear in less than 2% of the sentences in the dataset.</p>
<div class="sourceCode" id="cb136"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb136-1"><a href="supervised-methods.html#cb136-1" aria-hidden="true" tabindex="-1"></a>doc_matrix <span class="ot">&lt;-</span> <span class="fu">create_matrix</span>(USCongress<span class="sc">$</span>text, <span class="at">language =</span> <span class="st">&quot;english&quot;</span>, <span class="at">removeNumbers =</span> <span class="cn">TRUE</span>, <span class="at">stemWords =</span> <span class="cn">TRUE</span>, <span class="at">removeSparseTerms =</span> <span class="fl">0.998</span>)</span></code></pre></div>
<pre><code>## Warning in TermDocumentMatrix.SimpleCorpus(x, control): custom functions are
## ignored</code></pre>
<pre><code>## Warning in TermDocumentMatrix.SimpleCorpus(x, control): custom tokenizer is
## ignored</code></pre>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="supervised-methods.html#cb139-1" aria-hidden="true" tabindex="-1"></a>doc_matrix</span></code></pre></div>
<pre><code>## &lt;&lt;DocumentTermMatrix (documents: 4449, terms: 1015)&gt;&gt;
## Non-/sparse entries: 46473/4469262
## Sparsity           : 99%
## Maximal term length: 18
## Weighting          : term frequency (tf)</code></pre>
<p>Note that <code>RTextTools</code> gives you plenty of options in preprocessing. Apart from the options used above, you can also strip whitespace, remove punctuation, and remove stopwords from lists that are already defined in the package. Stemming and stopword removal is language specific, so when you select the language in the option as above <code>(language=''english'')</code>, the stemming and stopword removal will be done according to the language of your choice. At the moment, the stopwords included are those for Danish, Dutch, English, Finnish, French, German, Italian, Norwegian, Portuguese, Russian, Spanish, and Swedish.</p>
<p>We then create a container parsing the document matrix into a training set, and a test set. The training set will be used to train the algorithm and the test set to test how well this algorithm was trained. The following command instructs R to use the first 4000 sentences for the training set the remaining 449 sentences for the test set. Moreover, we specify to append to the document matrix the variable that contains the assigned coders:</p>
<div class="sourceCode" id="cb141"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb141-1"><a href="supervised-methods.html#cb141-1" aria-hidden="true" tabindex="-1"></a>container <span class="ot">&lt;-</span> <span class="fu">create_container</span>(doc_matrix, USCongress<span class="sc">$</span>major, <span class="at">trainSize =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">4000</span>, <span class="at">testSize =</span> <span class="dv">4001</span><span class="sc">:</span><span class="dv">4449</span>, <span class="at">virgin =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<p>We can then train a model using one of the available algorithms. For instance, we can use the Support Vector Machines algorithm (SVM) as follows:</p>
<div class="sourceCode" id="cb142"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb142-1"><a href="supervised-methods.html#cb142-1" aria-hidden="true" tabindex="-1"></a>SVM <span class="ot">&lt;-</span> <span class="fu">train_model</span>(container, <span class="st">&quot;SVM&quot;</span>)</span></code></pre></div>
<p>Other algorithms available are glmnet (GLMNET), maximum entropy (MAXENT), scaled linear discriminant analysis (SLDA), bagging (BAGGING), boosting (BOOSTING), random forest (RF), neural networks (NNET), classification tree (TREE).</p>
<p>We then use the model we just trained to classify the texts in the test set. The following command instructs R to classify the documents in the test set of the container using the SVM model that we previously trained.</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="supervised-methods.html#cb143-1" aria-hidden="true" tabindex="-1"></a>SVM_CLASSIFY <span class="ot">&lt;-</span> <span class="fu">classify_model</span>(container, SVM)</span></code></pre></div>
<p>We can also view the classification that was performed by the SVM model as follows. The first columns corresponds to the label that was assigned to each of the 449 sentences in the training set, while the second column gives the probability that the sentence was assigned to that particular category by the SVM algorithm. As you can see, while the probability for some sentences is quite high (e.g. 0.99 for sentence 3) for others is quite low (e.g. 0.13 for sentence 20) even though the classification always chooses the category with the highest probability.</p>
<div class="sourceCode" id="cb144"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb144-1"><a href="supervised-methods.html#cb144-1" aria-hidden="true" tabindex="-1"></a><span class="fu">View</span>(SVM_CLASSIFY)</span></code></pre></div>
<p>The next step is to check the performance of the model we just tested in terms of classification. To do this, we first request a function which returns a container with different summaries. For instance, we can request summaries on the basis of the labels that were attached to the sentences, the documents (or in this case, the sentences) by label, or on the basis of the algorithm.</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="supervised-methods.html#cb145-1" aria-hidden="true" tabindex="-1"></a>analytics <span class="ot">&lt;-</span> <span class="fu">create_analytics</span>(container,<span class="fu">cbind</span>(SVM_CLASSIFY))</span>
<span id="cb145-2"><a href="supervised-methods.html#cb145-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(analytics)</span></code></pre></div>
<pre><code>## ENSEMBLE SUMMARY
## 
##        n-ENSEMBLE COVERAGE n-ENSEMBLE RECALL
## n &gt;= 1                   1              0.74
## 
## 
## ALGORITHM PERFORMANCE
## 
## SVM_PRECISION    SVM_RECALL    SVM_FSCORE 
##        0.6370        0.6355        0.6270</code></pre>
<p>Precision gives the proportion of bills that were classified as belonging to a category and actually belong to this category (true positives) to all the bills that were classified in that category (irrespective of where they belong). Recall is the proportion of bills that were classified as belonging to a category and actually belong to this category (true positives) to all the bills that belong to this category (true positives plus false negatives). The F score is a weighted average between precision and recall ranging fro 0 to 1.</p>
<p>Instead of using a seperate package, we can also use <code>quanteda</code> to carry out an SVM. For this, we again load the reviews we used earlier, select 1000 of them at random, and place them into our corpus:</p>
<div class="sourceCode" id="cb147"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb147-1"><a href="supervised-methods.html#cb147-1" aria-hidden="true" tabindex="-1"></a><span class="fu">detach</span>(<span class="st">&quot;package:RTextTools&quot;</span>, <span class="at">unload =</span> <span class="cn">TRUE</span>)</span>
<span id="cb147-2"><a href="supervised-methods.html#cb147-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb147-3"><a href="supervised-methods.html#cb147-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb147-4"><a href="supervised-methods.html#cb147-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb147-5"><a href="supervised-methods.html#cb147-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(quanteda.classifiers)</span>
<span id="cb147-6"><a href="supervised-methods.html#cb147-6" aria-hidden="true" tabindex="-1"></a>corpus_reviews <span class="ot">&lt;-</span> <span class="fu">corpus_sample</span>(data_corpus_LMRD, <span class="dv">1000</span>)</span></code></pre></div>
<p>Our aim here will be to see how well the SVM algorithm can predict the rating of the reviews. To do this, we first have to create a new variable <code>prediction</code>. This variable contains the same scores as the original rating. Then, we remove 30% of the scores and replace them with NA. We do so by creating a <code>missing</code> variable what contains 30% 0s and 70% 1s. We then place the 0s with NAs. These NA scores are then the ones we want the algorithm to predict. Finally, we add the new variable to the corpus:</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="supervised-methods.html#cb148-1" aria-hidden="true" tabindex="-1"></a>prediction <span class="ot">&lt;-</span> corpus_reviews<span class="sc">$</span>rating</span>
<span id="cb148-2"><a href="supervised-methods.html#cb148-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb148-3"><a href="supervised-methods.html#cb148-3" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb148-4"><a href="supervised-methods.html#cb148-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb148-5"><a href="supervised-methods.html#cb148-5" aria-hidden="true" tabindex="-1"></a>missing <span class="ot">&lt;-</span> <span class="fu">rbinom</span>(<span class="dv">1000</span>, <span class="dv">1</span>, <span class="fl">0.7</span>)</span>
<span id="cb148-6"><a href="supervised-methods.html#cb148-6" aria-hidden="true" tabindex="-1"></a>prediction[missing <span class="sc">==</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb148-7"><a href="supervised-methods.html#cb148-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb148-8"><a href="supervised-methods.html#cb148-8" aria-hidden="true" tabindex="-1"></a><span class="fu">docvars</span>(corpus_reviews, <span class="st">&quot;prediction&quot;</span>) <span class="ot">&lt;-</span> prediction</span></code></pre></div>
<p>We then transform the corpus into a data frame, and also remove stopwords, numbers and punctuation:</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="supervised-methods.html#cb149-1" aria-hidden="true" tabindex="-1"></a>dfm_reviews <span class="ot">&lt;-</span> <span class="fu">dfm</span>(corpus_reviews, <span class="at">remove =</span> <span class="fu">stopwords</span>(<span class="st">&quot;english&quot;</span>), <span class="at">remove_punct =</span> <span class="cn">TRUE</span>, <span class="at">remove_numbers =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p>Now we can run the SVM algorithm. To do so, we tell the model on which dfm we want to run our model, and which variable contains the scores to train the algorithm. Here, this is our <code>prediction</code> variable with the missing data:</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="supervised-methods.html#cb150-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(quanteda.textmodels)</span>
<span id="cb150-2"><a href="supervised-methods.html#cb150-2" aria-hidden="true" tabindex="-1"></a>svm_reviews <span class="ot">&lt;-</span> <span class="fu">textmodel_svm</span>(dfm_reviews, <span class="at">y =</span> <span class="fu">docvars</span>(dfm_reviews, <span class="st">&quot;prediction&quot;</span>))</span>
<span id="cb150-3"><a href="supervised-methods.html#cb150-3" aria-hidden="true" tabindex="-1"></a>svm_reviews</span></code></pre></div>
<pre><code>## 
## Call:
## textmodel_svm.dfm(x = dfm_reviews, y = docvars(dfm_reviews, &quot;prediction&quot;))
## 
## 707 training documents; 129,216 fitted features.
## Method: L2-regularized L2-loss support vector classification dual (L2R_L2LOSS_SVC_DUAL)</code></pre>
<p>Here we see that the algorithm used 720 texts to train the model (the one with a score) and fitted 133,728 features. The latter refers to the total number of words in the training texts and not only the unique ones. Now we can use this model to predict the ratings we removed earlier:</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="supervised-methods.html#cb152-1" aria-hidden="true" tabindex="-1"></a>svm_predict <span class="ot">&lt;-</span> <span class="fu">predict</span>(svm_reviews)</span></code></pre></div>
<p>While we can of course look at the resulting numbers, we can also place them in a two-way table with the actual rating, to see how well the algorithm did:</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="supervised-methods.html#cb153-1" aria-hidden="true" tabindex="-1"></a>rating <span class="ot">&lt;-</span> corpus_reviews<span class="sc">$</span>rating</span>
<span id="cb153-2"><a href="supervised-methods.html#cb153-2" aria-hidden="true" tabindex="-1"></a>table_data <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">cbind</span>(svm_predict,rating))</span>
<span id="cb153-3"><a href="supervised-methods.html#cb153-3" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(table_data<span class="sc">$</span>svm_predict,table_data<span class="sc">$</span>rating)</span></code></pre></div>
<pre><code>##     
##        1   2   3   4   7   8   9  10
##   1  175  14  10  11   4   3   1   6
##   2   13  65   5   3   0   0   0   3
##   3    5   2  82   4   1   4   0   3
##   4    4   5   5  90   1   5   2   6
##   7    0   1   2   2  75   6   0   1
##   8    2   1   1   0   3  83   5   7
##   9    3   0   1   6   4  11  74   7
##   10   1   3   3   2   3  10  14 137</code></pre>
<p>Here, the table shows the prediction of the algorithm from top to bottom and the original rating from left to right. What we want is that all cases are on the diagonal: in that case, the prediction is the same as the original rating. Here, this happens in the majority of cases. Also, only in a few cases is the algorithm far off.</p>
</div>
<div id="naive-bayes" class="section level2" number="7.2">
<h2><span class="header-section-number">7.2</span> Naive Bayes</h2>
<p>For the NB example, we will use data from the Manifesto Project <span class="citation">(<a href="references.html#ref-Volkens2019a" role="doc-biblioref">Volkens et al. 2019</a>)</span>, also known as the Comparative Manifesto Project (CMP), Manifesto Research Group (MRG), and MARPOR (Manifesto Research on Political Representation)). After you have signed up and downloaded the API key, load the package and set the key:</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="supervised-methods.html#cb155-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(manifestoR)</span>
<span id="cb155-2"><a href="supervised-methods.html#cb155-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mp_setapikey</span>(<span class="st">&quot;manifesto_apikey.txt&quot;</span>)</span></code></pre></div>
<p>While we can download the whole dataset, as it is rather large, it makes more sense to only download download a part of it. Here, we take the manifestos for the United Kingdom in 2015. To tell R we want only these documents, we make a small dataframe listing the party and the year we want, and then place this into the <code>mp_corpus</code> command. Note that instead of the names of the parties, the Manifesto Project assigns unique codes to each party. To see which code belongs to which party, see: <a href="https://manifesto-project.wzb.eu/down/data/2019a/codebooks/parties_MPDataset_MPDS2019a.pdf" class="uri">https://manifesto-project.wzb.eu/down/data/2019a/codebooks/parties_MPDataset_MPDS2019a.pdf</a>. Also note that the date includes both the year and month of the election:</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="supervised-methods.html#cb156-1" aria-hidden="true" tabindex="-1"></a>manifestos <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">party=</span><span class="fu">c</span>(<span class="dv">51320</span>, <span class="dv">51620</span>, <span class="dv">51110</span>, <span class="dv">51421</span>, <span class="dv">51901</span>, <span class="dv">51902</span>, <span class="dv">51951</span>), <span class="at">date=</span><span class="fu">c</span>(<span class="dv">201505</span>, <span class="dv">201505</span>, <span class="dv">201505</span>, <span class="dv">201505</span>, <span class="dv">201505</span>, <span class="dv">201505</span>, <span class="dv">201505</span>))</span>
<span id="cb156-2"><a href="supervised-methods.html#cb156-2" aria-hidden="true" tabindex="-1"></a>manifesto_corpus <span class="ot">&lt;-</span> <span class="fu">mp_corpus</span>(manifestos)</span></code></pre></div>
<pre><code>## Connecting to Manifesto Project DB API... corpus version: 2020-2 
## Connecting to Manifesto Project DB API... corpus version: 2020-2</code></pre>
<p>For now, we are only interested in the (quasi)-sentences the of the manifestos, the codes the coders gave them, and names of the parties. To make everything more clear, we will take these elements from the corpus, combine them into a new data-frame, and remove all the NA values. We do this because otherwise the data would also include the headers and titles of the document, which do not have any codes assigned to them:</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="supervised-methods.html#cb158-1" aria-hidden="true" tabindex="-1"></a><span class="fu">detach</span>(<span class="st">&quot;package:httr&quot;</span>, <span class="at">unload =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## Warning: &#39;httr&#39; namespace cannot be unloaded:
##   namespace &#39;httr&#39; is imported by &#39;tidyverse&#39;, &#39;rvest&#39; so cannot be unloaded</code></pre>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="supervised-methods.html#cb160-1" aria-hidden="true" tabindex="-1"></a>text_51320 <span class="ot">&lt;-</span> <span class="fu">content</span>(manifesto_corpus[[<span class="st">&quot;51320_201505&quot;</span>]])</span>
<span id="cb160-2"><a href="supervised-methods.html#cb160-2" aria-hidden="true" tabindex="-1"></a>text_51620 <span class="ot">&lt;-</span> <span class="fu">content</span>(manifesto_corpus[[<span class="st">&quot;51620_201505&quot;</span>]])</span>
<span id="cb160-3"><a href="supervised-methods.html#cb160-3" aria-hidden="true" tabindex="-1"></a>text_51110 <span class="ot">&lt;-</span> <span class="fu">content</span>(manifesto_corpus[[<span class="st">&quot;51110_201505&quot;</span>]])</span>
<span id="cb160-4"><a href="supervised-methods.html#cb160-4" aria-hidden="true" tabindex="-1"></a>text_51421 <span class="ot">&lt;-</span> <span class="fu">content</span>(manifesto_corpus[[<span class="st">&quot;51421_201505&quot;</span>]])</span>
<span id="cb160-5"><a href="supervised-methods.html#cb160-5" aria-hidden="true" tabindex="-1"></a>text_51901 <span class="ot">&lt;-</span> <span class="fu">content</span>(manifesto_corpus[[<span class="st">&quot;51901_201505&quot;</span>]])</span>
<span id="cb160-6"><a href="supervised-methods.html#cb160-6" aria-hidden="true" tabindex="-1"></a>text_51902 <span class="ot">&lt;-</span> <span class="fu">content</span>(manifesto_corpus[[<span class="st">&quot;51902_201505&quot;</span>]])</span>
<span id="cb160-7"><a href="supervised-methods.html#cb160-7" aria-hidden="true" tabindex="-1"></a>text_51951 <span class="ot">&lt;-</span> <span class="fu">content</span>(manifesto_corpus[[<span class="st">&quot;51951_201505&quot;</span>]])</span>
<span id="cb160-8"><a href="supervised-methods.html#cb160-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb160-9"><a href="supervised-methods.html#cb160-9" aria-hidden="true" tabindex="-1"></a>texts <span class="ot">&lt;-</span> <span class="fu">c</span>(text_51320,text_51620,text_51110,text_51421,text_51901,text_51902,text_51951)</span>
<span id="cb160-10"><a href="supervised-methods.html#cb160-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb160-11"><a href="supervised-methods.html#cb160-11" aria-hidden="true" tabindex="-1"></a>party_51320 <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">51320</span>,<span class="at">length.out=</span><span class="fu">length</span>(text_51320))</span>
<span id="cb160-12"><a href="supervised-methods.html#cb160-12" aria-hidden="true" tabindex="-1"></a>party_51620 <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">51620</span>,<span class="at">length.out=</span><span class="fu">length</span>(text_51620))</span>
<span id="cb160-13"><a href="supervised-methods.html#cb160-13" aria-hidden="true" tabindex="-1"></a>party_51110 <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">51110</span>,<span class="at">length.out=</span><span class="fu">length</span>(text_51110))</span>
<span id="cb160-14"><a href="supervised-methods.html#cb160-14" aria-hidden="true" tabindex="-1"></a>party_51421 <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">51421</span>,<span class="at">length.out=</span><span class="fu">length</span>(text_51421))</span>
<span id="cb160-15"><a href="supervised-methods.html#cb160-15" aria-hidden="true" tabindex="-1"></a>party_51901 <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">51901</span>,<span class="at">length.out=</span><span class="fu">length</span>(text_51901))</span>
<span id="cb160-16"><a href="supervised-methods.html#cb160-16" aria-hidden="true" tabindex="-1"></a>party_51902 <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">51902</span>,<span class="at">length.out=</span><span class="fu">length</span>(text_51902))</span>
<span id="cb160-17"><a href="supervised-methods.html#cb160-17" aria-hidden="true" tabindex="-1"></a>party_51951 <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="dv">51951</span>,<span class="at">length.out=</span><span class="fu">length</span>(text_51951))</span>
<span id="cb160-18"><a href="supervised-methods.html#cb160-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb160-19"><a href="supervised-methods.html#cb160-19" aria-hidden="true" tabindex="-1"></a>party <span class="ot">&lt;-</span> <span class="fu">c</span>(party_51320,party_51620,party_51110,party_51421,party_51901,party_51902,party_51951)</span>
<span id="cb160-20"><a href="supervised-methods.html#cb160-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb160-21"><a href="supervised-methods.html#cb160-21" aria-hidden="true" tabindex="-1"></a>cmp_code <span class="ot">&lt;-</span> <span class="fu">codes</span>(manifesto_corpus)</span>
<span id="cb160-22"><a href="supervised-methods.html#cb160-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb160-23"><a href="supervised-methods.html#cb160-23" aria-hidden="true" tabindex="-1"></a>manifesto_data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(texts,cmp_code,party)</span></code></pre></div>
<p>Before we go on, we have to transform the columns in our data-frame. This is because R considers two of them (<em>texts</em> and <em>cmp_code</em>) to be a factor, and also still uses the codes for the <em>party</em> variable. To solve the latter, we first transform <em>party</em> into a factor type, then assign the party names to each of the codes (Conservatives, Labour, Liberal Democrats, SNP, Plaid Cymru, The Greens, and UKIP), and then change the column to character type. We then change the <strong>texts</strong> column to character and the <strong>cmp_code</strong> column to numeric. We also create a back-up of our current dfm for later, and finally remove any missing data:</p>
<div class="sourceCode" id="cb161"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb161-1"><a href="supervised-methods.html#cb161-1" aria-hidden="true" tabindex="-1"></a>manifesto_data<span class="sc">$</span>party <span class="ot">&lt;-</span> <span class="fu">factor</span>(manifesto_data<span class="sc">$</span>party,<span class="at">levels =</span> <span class="fu">c</span>(<span class="dv">51110</span>, <span class="dv">51320</span>, <span class="dv">51421</span>, <span class="dv">51620</span>, <span class="dv">51901</span>, <span class="dv">51902</span>, <span class="dv">51951</span>), <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;GREEN&quot;</span>, <span class="st">&quot;LABOUR&quot;</span>, <span class="st">&quot;LIBDEM&quot;</span>, <span class="st">&quot;CON&quot;</span>, <span class="st">&quot;PC&quot;</span>, <span class="st">&quot;SNP&quot;</span>, <span class="st">&quot;UKIP&quot;</span>)) </span>
<span id="cb161-2"><a href="supervised-methods.html#cb161-2" aria-hidden="true" tabindex="-1"></a>manifesto_data<span class="sc">$</span>party <span class="ot">&lt;-</span> <span class="fu">as.character</span>(manifesto_data<span class="sc">$</span>party)</span>
<span id="cb161-3"><a href="supervised-methods.html#cb161-3" aria-hidden="true" tabindex="-1"></a>manifesto_data<span class="sc">$</span>texts <span class="ot">&lt;-</span> <span class="fu">as.character</span>(manifesto_data<span class="sc">$</span>texts)</span>
<span id="cb161-4"><a href="supervised-methods.html#cb161-4" aria-hidden="true" tabindex="-1"></a>manifesto_data<span class="sc">$</span>cmp_code <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(manifesto_data<span class="sc">$</span>cmp_code))</span>
<span id="cb161-5"><a href="supervised-methods.html#cb161-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb161-6"><a href="supervised-methods.html#cb161-6" aria-hidden="true" tabindex="-1"></a>manifesto_data_raw <span class="ot">&lt;-</span> manifesto_data</span>
<span id="cb161-7"><a href="supervised-methods.html#cb161-7" aria-hidden="true" tabindex="-1"></a>manifesto_data <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(manifesto_data)</span></code></pre></div>
<p>In our data-frame, the <em>text</em> variable indicates the hand-coded quasi-sentences, while the <em>cmp_code</em> indicates the code it received. There are 56 categories in the Manifesto Project coding scheme, and an extra empty category indicated with 0. Before we go on, it might be interesting to see which parties have which codes assigned to them. The most simplest way to do this so is to make a cross-table of the parties and the codes. We can do this with the <code>table()</code> command:</p>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="supervised-methods.html#cb162-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(manifesto_data<span class="sc">$</span>cmp_code,manifesto_data<span class="sc">$</span>party)</span></code></pre></div>
<pre><code>##      
##       CON GREEN LABOUR LIBDEM  PC SNP UKIP
##   0    15    25      5      0   8   0    0
##   101   0     5      0      6   0   0    3
##   103   0     0      0      2   0   0    0
##   104   5    45      0     96   7  18   63
##   105  21    14      2     16   9  16   16
##   106  18    22      2      8   5   1    2
##   107  76    62     22     98  16  11   13
##   108  17    44      4     42   7  22    9
##   109   5     0      0      0   5   0   17
##   110   8     2      2     86   3   1  222
##   201  51   153      4     39   8  11   13
##   202  60   113      9     23  20  21   24
##   203   1     0      0      5   1   0    0
##   204  15    19      0     15   4   3    1
##   301  62   116      3     67  58 102   28
##   303   8    28      1     41   3   3   43
##   304  14     1      5      4   0   0   11
##   305  20     1     14      7   4   9   10
##   401   3     4      0     25   0   0   11
##   402   8    24      2     42  11  54   50
##   403 164   137     56     80  48  68   70
##   404   4     2      0     93   2  20   14
##   405   3     3      0      0   1  10    0
##   406   0     7      2      7   2   4   39
##   407   0     0      0      0   0   0    8
##   408  16     0      4      1   2   2    2
##   409   9     4      7      9   1  24    3
##   410  11    30      2     35  10  16    0
##   411  70    87      7     89  49  51   12
##   412  18    10      8      9   9  17    2
##   413  38     4     32      0  12   7    4
##   414  43    36      0     53   0  16   15
##   416  39    49    129     16   7  15   36
##   501 157   220    295     66  49  32   20
##   502  14    30      0     34  42   9   13
##   503 220   324    184     74 105  74   47
##   504 212   221    131    138  91 124  204
##   505   1    10      0     30   0   0   18
##   506 125    86      6     82  27  39   70
##   601  27    17      1     66   2   1  114
##   602   0     0      0      0  17  21    0
##   603   3     3      0     13   0   0    2
##   604   1     1      0      0   0   0    0
##   605   6   137      4    134   1  24   65
##   606  57    27     27     35  33   1    3
##   607  12    10      0      2  43   2    0
##   608   2     6      0      6   0   0   10
##   701  91    60     29     25  31  26   19
##   702   0     0      0     12   0   0    0
##   703   0    34      2     21  22  17   22
##   706   2     1      9      1   1   0    0</code></pre>
<p>Here we see that some codes such as 604 and 407 are rare, while others such as 501 and 504 occur far more often. When we look at the codebook the coders used (<a href="https://manifesto-project.wzb.eu/coding_schemes/mp_v5" class="uri">https://manifesto-project.wzb.eu/coding_schemes/mp_v5</a>), we find that 604 and 407 refer to <em>Traditional Morality: Negative</em> and <em>Protectionism: Negative</em>, while 501 and 504 refer to <em>Environmental Protection</em> and <em>Welfare State Expansion</em>. As such, it should also come as no surprise that the Green Party refers more to environmental protection than all other parties combined.</p>
<p>To get an even better idea of how much a party “owns” a code, we can calculate the row percentages. These inform us how much of the appearance of a certain code is due to a single party. To calculate these, we use the <code>prop.table</code> command. Here, the <code>,1</code> at the end tells R to look at the rows (no value would give the cell proportions, and 2 would give the column proportions). We then multiply the proportions by 100 to get the percentages. Then, we place the output in a data-frame, and provide some names to the columns using the <code>names</code> command:</p>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="supervised-methods.html#cb164-1" aria-hidden="true" tabindex="-1"></a>prop_row <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>((<span class="fu">prop.table</span>(<span class="fu">table</span>(manifesto_data<span class="sc">$</span>cmp_code,manifesto_data<span class="sc">$</span>party),<span class="dv">1</span>) <span class="sc">*</span> <span class="dv">100</span>))</span>
<span id="cb164-2"><a href="supervised-methods.html#cb164-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(prop_row) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Code&quot;</span>, <span class="st">&quot;Party&quot;</span>, <span class="st">&quot;Percentage&quot;</span>)</span></code></pre></div>
<p>While we can look at the results by looking at the <code>prop_row</code> object, it is clearer to do this in a graph. To build this graph, in the command we first specify the data, the x variable (the codes), the y variable (the percentages), and the filling of the bar (which should be the party colours). These party colours we provide in the next line (in hexadecimal notation). Then we tell <code>ggplot</code> to draw the bar chart and <em>stack</em> the bars on top of each other (the alternative is to <em>dodge</em>, in which R places the bars next to each other). Then, we specify our theme, turn the text for the codes 90 degrees, and move the codes a little bit so they are under their respective bars:</p>
<div class="sourceCode" id="cb165"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb165-1"><a href="supervised-methods.html#cb165-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb165-2"><a href="supervised-methods.html#cb165-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb165-3"><a href="supervised-methods.html#cb165-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>prop_row, <span class="fu">aes</span>(<span class="at">x=</span>Code, <span class="at">y=</span>Percentage, <span class="at">fill=</span>Party)) <span class="sc">+</span></span>
<span id="cb165-4"><a href="supervised-methods.html#cb165-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="st">&quot;&quot;</span>, <span class="at">values =</span> <span class="fu">c</span>(<span class="st">&quot;#0087DC&quot;</span>,<span class="st">&quot;#67B437&quot;</span>,<span class="st">&quot;#DC241F&quot;</span>,<span class="st">&quot;#FAA61A&quot;</span>,<span class="st">&quot;#008142&quot;</span>,<span class="st">&quot;#FDF38E&quot;</span>,<span class="st">&quot;#780077&quot;</span>))<span class="sc">+</span></span>
<span id="cb165-5"><a href="supervised-methods.html#cb165-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">position =</span> <span class="st">&quot;stack&quot;</span>) <span class="sc">+</span></span>
<span id="cb165-6"><a href="supervised-methods.html#cb165-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb165-7"><a href="supervised-methods.html#cb165-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()<span class="sc">+</span></span>
<span id="cb165-8"><a href="supervised-methods.html#cb165-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>))<span class="sc">+</span></span>
<span id="cb165-9"><a href="supervised-methods.html#cb165-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">vjust =</span> <span class="fl">0.40</span>))</span></code></pre></div>
<p><img src="Quantitative-Text-Analysis_files/figure-html/unnamed-chunk-110-1.png" width="672" /></p>
<p>Now, we can see that some parties dominate some categories, while for others the spread is more even. For example, UKIP dominates the categories 406 and 407 - dealing with positive and negative mentions of protectionism, while the Conservatives do the same with category 103 (<em>Anti-Imperialism</em>). Note though, that these are percentages. This means that the reason the Conservatives dominate category 103 is as they have two (quasi)-sentences with that category. The others do not have the category at all (702 on <em>Negative Mentioning of Labour Groups</em> has the same issue). Other categories, such as 403 (<em>Market Regulation</em>) and 502 (<em>Positive Mentions of Culture</em>) are way better spread out over all the parties.</p>
<p>Another thing we can look at is what part of a party’s manifesto belongs to any of the codes. This can help us answer the question: “what are the parties talking about?” To see this, we have to calculate the column percentages:</p>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="supervised-methods.html#cb166-1" aria-hidden="true" tabindex="-1"></a>prop_col <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>((<span class="fu">prop.table</span>(<span class="fu">table</span>(manifesto_data<span class="sc">$</span>cmp_code,manifesto_data<span class="sc">$</span>party), <span class="dv">2</span>) <span class="sc">*</span> <span class="dv">100</span>))</span>
<span id="cb166-2"><a href="supervised-methods.html#cb166-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(prop_col) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Code&quot;</span>, <span class="st">&quot;Party&quot;</span>, <span class="st">&quot;Percentage&quot;</span>)</span></code></pre></div>
<p>If we now type <code>prop_col</code>, we can see what percentage of a party manifesto was about a certain code. Yet, given that there are 57 possible codes, it is more practical to cluster these in some way. Here, we do this using the Domains to which they belonged in the codebook. In total there are 7 domains (<a href="https://manifesto-project.wzb.eu/down/papers/handbook_2014_version_5.pdf" class="uri">https://manifesto-project.wzb.eu/down/papers/handbook_2014_version_5.pdf</a>), and a category which houses the 0 code. To cluster the codes, we make a new variable called <code>Domain</code>. To do so, we first transform the codes into numeric format, create an empty variable called <code>Domain</code>, and then replace the NA values in this empty category with the name of the domain based on the values in the Code variable. This we do using various operators R uses: <code>&gt;=</code> means greater than and equal to, while <code>&lt;=</code> means smaller than and equal to. Then, we make this new variable into a factor, and sort this factor in the way the codes occur:</p>
<div class="sourceCode" id="cb167"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb167-1"><a href="supervised-methods.html#cb167-1" aria-hidden="true" tabindex="-1"></a>prop_col<span class="sc">$</span>Code <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(prop_col<span class="sc">$</span>Code))</span>
<span id="cb167-2"><a href="supervised-methods.html#cb167-2" aria-hidden="true" tabindex="-1"></a>prop_col<span class="sc">$</span>Domain <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb167-3"><a href="supervised-methods.html#cb167-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb167-4"><a href="supervised-methods.html#cb167-4" aria-hidden="true" tabindex="-1"></a>prop_col<span class="sc">$</span>Domain[prop_col<span class="sc">$</span>Code <span class="sc">&gt;=</span> <span class="dv">101</span> <span class="sc">&amp;</span> prop_col<span class="sc">$</span>Code <span class="sc">&lt;=</span> <span class="dv">110</span>] <span class="ot">&lt;-</span> <span class="st">&quot;External Relations&quot;</span></span>
<span id="cb167-5"><a href="supervised-methods.html#cb167-5" aria-hidden="true" tabindex="-1"></a>prop_col<span class="sc">$</span>Domain[prop_col<span class="sc">$</span>Code <span class="sc">&gt;=</span> <span class="dv">201</span> <span class="sc">&amp;</span> prop_col<span class="sc">$</span>Code <span class="sc">&lt;=</span> <span class="dv">204</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Freedom and Democracy&quot;</span></span>
<span id="cb167-6"><a href="supervised-methods.html#cb167-6" aria-hidden="true" tabindex="-1"></a>prop_col<span class="sc">$</span>Domain[prop_col<span class="sc">$</span>Code <span class="sc">&gt;=</span> <span class="dv">301</span> <span class="sc">&amp;</span> prop_col<span class="sc">$</span>Code <span class="sc">&lt;=</span> <span class="dv">305</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Political System&quot;</span></span>
<span id="cb167-7"><a href="supervised-methods.html#cb167-7" aria-hidden="true" tabindex="-1"></a>prop_col<span class="sc">$</span>Domain[prop_col<span class="sc">$</span>Code <span class="sc">&gt;=</span> <span class="dv">401</span> <span class="sc">&amp;</span> prop_col<span class="sc">$</span>Code <span class="sc">&lt;=</span> <span class="dv">416</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Economy&quot;</span></span>
<span id="cb167-8"><a href="supervised-methods.html#cb167-8" aria-hidden="true" tabindex="-1"></a>prop_col<span class="sc">$</span>Domain[prop_col<span class="sc">$</span>Code <span class="sc">&gt;=</span> <span class="dv">501</span> <span class="sc">&amp;</span> prop_col<span class="sc">$</span>Code <span class="sc">&lt;=</span> <span class="dv">507</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Welfare and Quality of Life&quot;</span></span>
<span id="cb167-9"><a href="supervised-methods.html#cb167-9" aria-hidden="true" tabindex="-1"></a>prop_col<span class="sc">$</span>Domain[prop_col<span class="sc">$</span>Code <span class="sc">&gt;=</span> <span class="dv">601</span> <span class="sc">&amp;</span> prop_col<span class="sc">$</span>Code <span class="sc">&lt;=</span> <span class="dv">608</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Fabric of Society&quot;</span></span>
<span id="cb167-10"><a href="supervised-methods.html#cb167-10" aria-hidden="true" tabindex="-1"></a>prop_col<span class="sc">$</span>Domain[prop_col<span class="sc">$</span>Code <span class="sc">&gt;=</span> <span class="dv">701</span> <span class="sc">&amp;</span> prop_col<span class="sc">$</span>Code <span class="sc">&lt;=</span> <span class="dv">706</span>] <span class="ot">&lt;-</span> <span class="st">&quot;Social Groups&quot;</span></span>
<span id="cb167-11"><a href="supervised-methods.html#cb167-11" aria-hidden="true" tabindex="-1"></a>prop_col<span class="sc">$</span>Domain[prop_col<span class="sc">$</span>Code <span class="sc">==</span> <span class="dv">0</span>] <span class="ot">&lt;-</span> <span class="st">&quot;NA&quot;</span></span>
<span id="cb167-12"><a href="supervised-methods.html#cb167-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb167-13"><a href="supervised-methods.html#cb167-13" aria-hidden="true" tabindex="-1"></a>prop_col<span class="sc">$</span>Domain <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(prop_col<span class="sc">$</span>Domain)</span>
<span id="cb167-14"><a href="supervised-methods.html#cb167-14" aria-hidden="true" tabindex="-1"></a>prop_col<span class="sc">$</span>Domain <span class="ot">&lt;-</span> <span class="fu">factor</span>(prop_col<span class="sc">$</span>Domain,<span class="fu">levels</span>(prop_col<span class="sc">$</span>Domain)[<span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">4</span>,<span class="dv">6</span>,<span class="dv">1</span>,<span class="dv">8</span>,<span class="dv">3</span>,<span class="dv">7</span>,<span class="dv">5</span>)])</span></code></pre></div>
<p>We then construct a plot as we did above:</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="supervised-methods.html#cb168-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data=</span>prop_col, <span class="fu">aes</span>(<span class="at">x=</span>Party, <span class="at">y=</span>Percentage, <span class="at">fill=</span>Domain)) <span class="sc">+</span></span>
<span id="cb168-2"><a href="supervised-methods.html#cb168-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">&quot;identity&quot;</span>, <span class="at">position =</span> <span class="st">&quot;stack&quot;</span>) <span class="sc">+</span></span>
<span id="cb168-3"><a href="supervised-methods.html#cb168-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb168-4"><a href="supervised-methods.html#cb168-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()<span class="sc">+</span></span>
<span id="cb168-5"><a href="supervised-methods.html#cb168-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>))<span class="sc">+</span></span>
<span id="cb168-6"><a href="supervised-methods.html#cb168-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">vjust =</span> <span class="fl">0.40</span>))</span></code></pre></div>
<p><img src="Quantitative-Text-Analysis_files/figure-html/unnamed-chunk-113-1.png" width="672" /></p>
<p>Here, we see that the Domain of <em>Welfare and Quality of Life</em> was the most dominant in all the manifestos, with <em>Economy</em> coming second. Also, especially UKIP paid a lot of attention to <em>External Relations</em>, while the Green party paid little attention to the <em>Fabric of Society</em>. In all, this gives us a good idea of what type of data we are actually dealing with.</p>
<p>Now let’s get back to the classification. For this, we need to transform the corpus from the <code>manifestoR</code> package into a corpus for the <code>quanteda</code> package. To do so, we first have to transform the former into a data frame, and then turn it into a corpus. We then look at the first 10 entries:</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="supervised-methods.html#cb169-1" aria-hidden="true" tabindex="-1"></a>corpus_data <span class="ot">&lt;-</span> <span class="fu">mp_corpus</span>(manifestos) <span class="sc">%&gt;%</span> </span>
<span id="cb169-2"><a href="supervised-methods.html#cb169-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as.data.frame</span>(<span class="at">with.meta=</span><span class="cn">TRUE</span>)</span>
<span id="cb169-3"><a href="supervised-methods.html#cb169-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb169-4"><a href="supervised-methods.html#cb169-4" aria-hidden="true" tabindex="-1"></a>manifesto_corpus <span class="ot">&lt;-</span> <span class="fu">corpus</span>(corpus_data)</span>
<span id="cb169-5"><a href="supervised-methods.html#cb169-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb169-6"><a href="supervised-methods.html#cb169-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(manifesto_corpus, <span class="dv">10</span>)</span></code></pre></div>
<p>Here, we see that the corpus treats each sentence as a separate document (which is confusing). We can still identify to which party they belong due to the <em>party</em> variable, which shows the party code. The <em>cmp_code</em> variable shows the code assigned to the sentence (here it is all NA as the first sentences have the 0 category). To run the NB, instead of providing our training documents using a vector with NA values, we have to split our data-set into a training and a test set. For this, we first generate a string of 8000 random numbers between 0 and 10780 (the total number of sentences). We do so to prevent our training or test set to exist only of sentences from a single party document:</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="supervised-methods.html#cb170-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">42</span>)</span>
<span id="cb170-2"><a href="supervised-methods.html#cb170-2" aria-hidden="true" tabindex="-1"></a>id_train <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">10780</span>, <span class="dv">8000</span>, <span class="at">replace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb170-3"><a href="supervised-methods.html#cb170-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(id_train, <span class="dv">10</span>)</span></code></pre></div>
<pre><code>##  [1]  2369  5273  9290  1252  8826 10289   356  7700  3954 10095</code></pre>
<p>Then we generate a unique number for each of the 10780 sentences in our corpus. This so we can later match them to the sentences we would like to place in our training set or our test set:</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="supervised-methods.html#cb172-1" aria-hidden="true" tabindex="-1"></a><span class="fu">docvars</span>(manifesto_corpus, <span class="st">&quot;id_numeric&quot;</span>) <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">ndoc</span>(manifesto_corpus)</span></code></pre></div>
<p>We should now see this new variable <em>id_numeric</em> appear in our corpus. We can now construct our training and test set using these id’s. For the training set, the logic is to create a sub set of the main corpus, and to take only those sentences whose <em>id_numeric</em> is also in <em>id_train</em>. For the test set, we do the same, only now taking only those sentences whose <em>id_numeric</em> is not in <em>id_train</em> (note that the ! mark signifies this). Then, we use the <code>%&gt;%</code> pipe to transform the resulting object into a dfm:</p>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="supervised-methods.html#cb173-1" aria-hidden="true" tabindex="-1"></a>manifesto_train <span class="ot">&lt;-</span> <span class="fu">corpus_subset</span>(manifesto_corpus, id_numeric <span class="sc">%in%</span> id_train) <span class="sc">%&gt;%</span></span>
<span id="cb173-2"><a href="supervised-methods.html#cb173-2" aria-hidden="true" tabindex="-1"></a>    <span class="fu">dfm</span>()</span>
<span id="cb173-3"><a href="supervised-methods.html#cb173-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb173-4"><a href="supervised-methods.html#cb173-4" aria-hidden="true" tabindex="-1"></a>manifesto_test <span class="ot">&lt;-</span> <span class="fu">corpus_subset</span>(manifesto_corpus, <span class="sc">!</span>id_numeric <span class="sc">%in%</span> id_train) <span class="sc">%&gt;%</span></span>
<span id="cb173-5"><a href="supervised-methods.html#cb173-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">dfm</span>()</span></code></pre></div>
<p>We then run the model using the <code>textmodel_nb</code> command, and ask it to use as classifiers the codes in the <em>cmp_code</em> variable:</p>
<div class="sourceCode" id="cb174"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb174-1"><a href="supervised-methods.html#cb174-1" aria-hidden="true" tabindex="-1"></a>manifesto_nb <span class="ot">&lt;-</span> <span class="fu">textmodel_nb</span>(manifesto_train, <span class="fu">docvars</span>(manifesto_train, <span class="st">&quot;cmp_code&quot;</span>))</span>
<span id="cb174-2"><a href="supervised-methods.html#cb174-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(manifesto_nb)</span></code></pre></div>
<p>Notice that the textmodel gives us a prediction of how likely it is that an individual word belongs to a certain code (the estimated feature scores). While this can be interesting, what we want to know here is how good the algorithm was. This is when we move from the training of the model using the training set to the prediction of the test set.</p>
<p>A problem is that Naive Bayes can only use featuers that were both in the training and the test set. To ensure this happens, we use the <code>dfm_match</code> option, which matches all the features in our dfm to a specified vector of features:</p>
<div class="sourceCode" id="cb175"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb175-1"><a href="supervised-methods.html#cb175-1" aria-hidden="true" tabindex="-1"></a>manifesto_matched <span class="ot">&lt;-</span> <span class="fu">dfm_match</span>(manifesto_test, <span class="at">features =</span> <span class="fu">featnames</span>(manifesto_train))</span></code></pre></div>
<p>If we look at this new corpus we see that little has changed (there are still 2780 features). This means that all features that were in the test set were also there in the training set. This is good news as this means the algorithm has all the information needed for a good prediction. Yet, the lower the number of sentences, the less likely this is to occur, so matching is always a good idea.</p>
<p>Now we can predict the missing codes in the test set (now the manifesto_matched dfm) using the model we trained earlier. The resulting classes are what the model predicts (we already set this when we trained the model). If we would then open the <code>predicted_class</code> object we can see to which code R assigned each sentence. Yet, as before, this is a little too much information. Moreover, we do not want to know what the model assigned the sentence to, but how this corresponds to the original code. To see this, we take the actual classes from the <code>manifesto_matched</code> dfm and place them with the predicted classes into a cross table:</p>
<div class="sourceCode" id="cb176"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb176-1"><a href="supervised-methods.html#cb176-1" aria-hidden="true" tabindex="-1"></a>predicted_class <span class="ot">&lt;-</span> <span class="fu">predict</span>(manifesto_nb, <span class="at">newdata =</span> manifesto_matched)</span>
<span id="cb176-2"><a href="supervised-methods.html#cb176-2" aria-hidden="true" tabindex="-1"></a>actual_class <span class="ot">&lt;-</span> <span class="fu">docvars</span>(manifesto_matched, <span class="st">&quot;cmp_code&quot;</span>)</span>
<span id="cb176-3"><a href="supervised-methods.html#cb176-3" aria-hidden="true" tabindex="-1"></a>table_class <span class="ot">&lt;-</span> <span class="fu">table</span>(actual_class, predicted_class)</span>
<span id="cb176-4"><a href="supervised-methods.html#cb176-4" aria-hidden="true" tabindex="-1"></a>table_class</span></code></pre></div>
<p>While this is already better (we have to pay attention to the diagonal), the large number of codes still makes this hard to read. So, as before, we can better visualise these results - here with the help of a heatmap. To do this, we first tranform our table into a dataframe which gives us all the possible combinations of codes and their occurrence. We put this into the command and also use a scaling gradient that gets darker when the value in a cell is higher:</p>
<div class="sourceCode" id="cb177"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb177-1"><a href="supervised-methods.html#cb177-1" aria-hidden="true" tabindex="-1"></a>table_class <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(table_class)</span>
<span id="cb177-2"><a href="supervised-methods.html#cb177-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb177-3"><a href="supervised-methods.html#cb177-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> table_class, <span class="fu">aes</span>(<span class="at">x =</span> predicted_class, <span class="at">y =</span> actual_class)) <span class="sc">+</span></span>
<span id="cb177-4"><a href="supervised-methods.html#cb177-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_tile</span>(<span class="fu">aes</span>(<span class="at">fill =</span> Freq)) <span class="sc">+</span></span>
<span id="cb177-5"><a href="supervised-methods.html#cb177-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_gradient</span>(<span class="at">high =</span> <span class="st">&quot;black&quot;</span>, <span class="at">low =</span> <span class="st">&quot;white&quot;</span>, <span class="at">name=</span><span class="st">&quot;Value&quot;</span>)<span class="sc">+</span></span>
<span id="cb177-6"><a href="supervised-methods.html#cb177-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">&quot;Predicted Class&quot;</span>)<span class="sc">+</span></span>
<span id="cb177-7"><a href="supervised-methods.html#cb177-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">&quot;Actual Class&quot;</span>)<span class="sc">+</span></span>
<span id="cb177-8"><a href="supervised-methods.html#cb177-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_discrete</span>(<span class="at">expand =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">0</span>)) <span class="sc">+</span></span>
<span id="cb177-9"><a href="supervised-methods.html#cb177-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_classic</span>()<span class="sc">+</span></span>
<span id="cb177-10"><a href="supervised-methods.html#cb177-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>))<span class="sc">+</span></span>
<span id="cb177-11"><a href="supervised-methods.html#cb177-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">vjust =</span> <span class="fl">0.40</span>))</span></code></pre></div>
<p><img src="Quantitative-Text-Analysis_files/figure-html/unnamed-chunk-121-1.png" width="672" /></p>
<p>Here, we can see that a high number of cases are on the diagonal, which indicates that the algorithm did a good job. Yet, it also classified a large number of sentences into the 503 and 504 categories, while they belonged to any of the other categories.</p>
<p>Besides this, we can also summarize how good the algorithm is by means of Krippendorff’s <span class="math inline">\(\alpha\)</span>. To do so, we take the predicted codes, transform them from factors to numeric values, and store them in an object. Then, we bind them together with the actual codes and place them into a data frame. Finally, we transpose the data frame (so that rows are now columns) and make it into a matrix:</p>
<div class="sourceCode" id="cb178"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb178-1"><a href="supervised-methods.html#cb178-1" aria-hidden="true" tabindex="-1"></a>predict <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">as.character</span>(predicted_class))</span>
<span id="cb178-2"><a href="supervised-methods.html#cb178-2" aria-hidden="true" tabindex="-1"></a>reliability <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(<span class="fu">cbind</span>(actual_class, predict))</span>
<span id="cb178-3"><a href="supervised-methods.html#cb178-3" aria-hidden="true" tabindex="-1"></a>reliability_t <span class="ot">&lt;-</span> <span class="fu">t</span>(reliability)</span>
<span id="cb178-4"><a href="supervised-methods.html#cb178-4" aria-hidden="true" tabindex="-1"></a>reliability <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(reliability_t)</span></code></pre></div>
<p>Then, we load the <code>kripp.boot</code> package, and calculate the nominal version of Krippendorff’s <span class="math inline">\(\alpha\)</span>, as we are working with nominal codes:</p>
<div class="sourceCode" id="cb179"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb179-1"><a href="supervised-methods.html#cb179-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kripp.boot)</span>
<span id="cb179-2"><a href="supervised-methods.html#cb179-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kripp.boot</span>(reliability, <span class="at">iter =</span> <span class="dv">500</span>, <span class="at">method =</span> <span class="st">&quot;nominal&quot;</span>)</span></code></pre></div>
<p>Here we see that the number of subjects was 2780 (the number of sentences in the test set), the number of coders 2 (the actual and the predicted codes), and the value of <span class="math inline">\(\alpha\)</span> 0.318 with an interval between 0.297 and 0.337. While this might not look particularly encouraging, when we realise that <span class="citation"><a href="references.html#ref-Mikhaylov2012a" role="doc-biblioref">Mikhaylov, Laver, and Benoit</a> (<a href="references.html#ref-Mikhaylov2012a" role="doc-biblioref">2012</a>)</span> estimate the agreement among trained coders by the Manifesto Project to be between 0.350 and 0.400, then 0.305 is quite a good score for a simple model!</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="scaling.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="unsupervised-methods.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Quantitative Text Analysis.pdf", "Quantitative Text Analysis.epub"],
"toc": {
"collapse": "subsection"
},
"toolbar": {
"position": "static"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
